# Generated by Django 5.0.13 on 2025-10-13 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.TextField()),
                ('project_description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('project_name',)},
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField()),
                ('file_type', models.TextField(default=None)),
                ('sheet_name', models.TextField(default=None, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='connection.project')),
            ],
            options={
                'unique_together': {('project_id', 'file_name', 'sheet_name')},
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_name', models.CharField(blank=True, max_length=255, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('sysnr', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.CharField(blank=True, max_length=255, null=True)),
                ('database', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_tables', models.JSONField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='connection.project')),
            ],
            options={
                'unique_together': {('project_id', 'connection_name')},
            },
        ),
        migrations.CreateModel(
            name='TableMeta',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField()),
                ('table_name', models.TextField()),
                ('primary_keys', models.TextField(blank=True, null=True)),
                ('preload', models.BooleanField(default=False)),
                ('postload', models.BooleanField(default=False)),
                ('source', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('connection_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='connection.connection')),
                ('file_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='connection.file')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='connection.project')),
            ],
            options={
                'unique_together': {('project_id', 'table_name')},
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_text', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='connection.project')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='connection.tablemeta')),
            ],
        ),
    ]
